serenity-bdd/serenity-documentation

- src/asciidoc/tags.adoc
Added to Chapter 13:
- how to annotate tests with tags in JUnit
- how to run scenarios by tags in JUnit and JBehave
> Chapter-13: JUnit tags; Running scenarios by tags in JUnit and JBehave

- src/asciidoc/junit.adoc
- src/samples/junit-quick-start/thucydides.properties
This is likely to affect other chapters as well, I only looked through the JUnit chapter.
> Renamed properties from thucydides.* to serenity.*

- src/asciidoc/junit.adoc
- src/asciidoc/maven.adoc
> Doc updates of noted Thucydides -> Serenity changes in product.

- src/asciidoc/advanced-webdriver.adoc
Problem:
some code in this paragraph wasn't code but simple text.
> Pull request for fixing Custom WebDriver implementations markers

- src/asciidoc/retry.adoc
Problem:
using of max.retries is unclear. It is quite difficult to understand how many times test will be run if max.retries will be 2 for example. Will be it run 2 or 3 times? )
> Pull request for updating max.retries description

- src/asciidoc/remote.adoc
Problem:
Running tests against pharagraph contains incorrect  branch in the end of Grid2[Selenium Grid]]
> Pull request for removing branch from text in Running tests against pharagraph

- src/asciidoc/page-objects.adoc
Problem: 
Explicit Timeouts was not paragraph but text, started from ====
> Pull requst for updating page-object, explicit timouts pharagraph fix

- src/asciidoc/screenshots.adoc
- src/asciidoc/system-props.adoc
Here is update of documentation based on update  [191 pull request](https://github.com/serenity-bdd/serenity-core/pull/191)
> Pull request for adding new level of screenshot mode

- src/asciidoc/cucumber.adoc
- src/asciidoc/index.adoc
- src/asciidoc/jbehave.adoc
- src/asciidoc/junit.adoc
- src/asciidoc/steps.adoc
- src/asciidoc/system-props.adoc
Problem:
Here is #10 pull request, that can not merged before. It had some merge conflicts
Reason: 
Some updates, that conflict with master branch. 
Solution:
New pull request was added. Changes was reviewed manually, and most all included in this pull request. Also some updates was added during reviewing - syntax errors, names, internal references, wrapping source code. 
@wakaleo please review it. And if all fine close both pull requests.
Thanks a lot!!!
> Pull requst to merge reviewed #10 pull requst

- src/asciidoc/advanced-webdriver.adoc
- src/asciidoc/junit.adoc
- src/asciidoc/page-objects.adoc
- src/asciidoc/screenshots.adoc
- src/asciidoc/spring.adoc
- src/asciidoc/steps.adoc
- src/asciidoc/system-props.adoc
Problem:
some java and xml not highlighted (#41  issue)
Reason
- no tag [source, java] and [source, xml]
Solution
added tags
> Pull requst for adding colors to manual for java and xml

- src/asciidoc/serenity-issues.adoc
Problem: 
in #45 reported about missed info in manual
Reason: 
not implemented
Solution: 
Added description for this behaving
> Pull request for updating chapter:  linking with issues by # in scenario name

- src/asciidoc/remote.adoc
Updated as per the https://www.browserstack.com/automate/capabilities website
> Updated the BrowserStack section to match the current argument set

- src/asciidoc/basic-concepts.adoc
Updated explanation of usage for @manual tag
issue #59
> Updated explanation of usage for @manual tag

- src/asciidoc/maven.adoc
Updated description for maven plugin based on issue #56
> Updated description for maven plugin

- src/asciidoc/system-props.adoc
Added chrome.switches examples based on issue serenity-bdd/serenity-core/issues/379
Related to issue #51
> Added chrome.switches examples

- src/asciidoc/junit.adoc
Added description for some new features for Managed
Related issue is #57
> Added description for some new features for Managed

- src/asciidoc/basic-concepts.adoc
- src/asciidoc/system-props.adoc
Updated description for output dir, fixed some spelling error
related issue is #53
> Updated description for output dir, fixed some spelling error

- src/asciidoc/retry.adoc
see https://github.com/serenity-bdd/serenity-core/issues/132
> Update retry docs for Jenkins usage

- src/asciidoc/remote.adoc
see https://github.com/serenity-bdd/serenity-core/issues/235
> Adding appium chapter

- src/asciidoc/tags.adoc
Added example of filtering test using tests for Cucumber
Added sub-chapters for JBehave, JUnit and Cucumber in the Tags chapter with examples 
N/A
N/A
N/A
#82 
N/A
> Added example of filtering test using tests for Cucumber

- src/asciidoc/basic-concepts.adoc
Added information about using Manual for the whole test only
Added information about usage of @Manual tag
N/A
N/A
N/A
#81 
N/A
> Added information about using Manual for the whole test only

- src/asciidoc/remote.adoc
Added examples of serenity.driver.capabilities usage
An example of configuring custom driver capabilities, such as OS, Browser and Version is provided
N/A
N/A
N/A
#62 
N/A
> Added examples of serenity.driver.capabilities usage

- src/asciidoc/basic-concepts.adoc
Corrected some grammar mistakes in documentation
Improved documentation
N/A
N/A
N/A
#95 
N/A
> Corrected grammar mistakes

- src/asciidoc/remote.adoc
@wakaleo please review and merge
Thanks & Regards,
Vikram
> https://github.com/serenity-bdd/serenity-core/issues/659 info is updated

- src/asciidoc/remote.adoc
Add browserstack.localIdentifier command line option information
> Update information about browserstack connections

- src/samples/junit-quick-start/pom.xml
It is confusing if in the example is a old artefact id
> Upgrade maven junit samples to latest versions

- src/asciidoc/page-objects.adoc
Please review PR for https://github.com/serenity-bdd/serenity-documentation/issues/123
> fixes for section 8.5 Working with timeouts
